name: Linter

on: [pull_request, workflow_dispatch]

jobs:
    linter:
        runs-on: namespace-profile-default
        steps:
            - name: Checkout branch
              uses: actions/checkout@v5

            - name: Run pre-commit
              uses: pre-commit/action@v3.0.1
